# Generated by Django 4.1.2 on 2022-10-07 15:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('budget', models.CharField(max_length=10)),
                ('month', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Purchased',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=500)),
                ('price', models.CharField(max_length=8)),
                ('date', models.CharField(max_length=500)),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['item'],
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=100)),
                ('price', models.CharField(max_length=8)),
                ('date', models.CharField(max_length=500)),
                ('buys', models.ManyToManyField(to='main_app.budget')),
            ],
        ),
        migrations.AddField(
            model_name='budget',
            name='purch',
            field=models.ForeignKey(null='True', on_delete=django.db.models.deletion.CASCADE, related_name='buys', to='main_app.purchased'),
        ),
    ]
