# Generated by Django 4.1.2 on 2022-10-12 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='buys',
            field=models.ManyToManyField(blank=True, related_name='buys', to='main_app.budget'),
        ),
    ]
