# Generated by Django 4.1.2 on 2022-10-07 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='purchased',
            options={'ordering': ['name']},
        ),
        migrations.RenameField(
            model_name='item',
            old_name='item',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='purchased',
            old_name='item',
            new_name='name',
        ),
    ]
