# Generated by Django 4.1.2 on 2022-10-07 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_alter_purchased_options_rename_item_item_title_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='budget',
            old_name='budget',
            new_name='title',
        ),
    ]
