# Generated by Django 4.1.2 on 2022-10-12 12:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_alter_item_buys'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchased',
            name='budget',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='budget', to='main_app.budget'),
        ),
    ]
