# Generated by Django 4.1.2 on 2022-10-07 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_rename_budget_budget_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='buys',
            field=models.ManyToManyField(to='main_app.purchased'),
        ),
    ]
