# Generated by Django 4.1.2 on 2022-10-14 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_alter_item_buys'),
        ('main_app', '0004_alter_purchased_budget'),
    ]

    operations = [
    ]
