# Generated by Django 4.1.2 on 2022-10-14 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_merge_20221014_1536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='buys',
            field=models.ManyToManyField(related_name='buys', to='main_app.budget'),
        ),
    ]
