# Generated by Django 4.1.2 on 2022-10-10 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_alter_item_buys'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='buys',
            field=models.ManyToManyField(blank=True, to='main_app.purchased'),
        ),
    ]
