# Generated by Django 4.1.2 on 2022-10-10 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0010_remove_budget_purch_remove_purchased_user_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='budget',
            old_name='title',
            new_name='amount',
        ),
    ]
