# Generated by Django 4.1.2 on 2022-10-10 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0011_rename_title_budget_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='buys',
            field=models.ManyToManyField(blank=True, related_name='buys', to='main_app.purchased'),
        ),
    ]
