# Generated by Django 4.1.2 on 2022-10-10 21:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0012_alter_item_buys'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchased',
            old_name='location',
            new_name='item',
        ),
    ]
