# Generated by Django 4.1.2 on 2022-10-11 16:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0014_purchased_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='purchased',
            options={},
        ),
        migrations.RemoveField(
            model_name='purchased',
            name='date',
        ),
        migrations.RemoveField(
            model_name='purchased',
            name='item',
        ),
        migrations.RemoveField(
            model_name='purchased',
            name='name',
        ),
        migrations.RemoveField(
            model_name='purchased',
            name='price',
        ),
        migrations.AddField(
            model_name='item',
            name='name',
            field=models.CharField(default='Nike', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='purchased',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
